version: '2'
services:
    postgres:
        image: postgres
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

    server:
        build: ./server
        command: ./main
        depends_on:
            - "postgres"
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        ports:
            - "8070:9000"
    client:
        build: ./client
        command: npm run prod 
        volumes:
            - ./client:/usr/src/app
            - /usr/src/app/node_modules
        ports:
            - "3000:3000"

