version: '2'
services:
    db:
        image: postgres
        environment:
            - POSTGRES_USER=supermaster
            - POSTGRES_PASSWORD=password1

    server:
        build: ./server
        command: ./main
        depends_on:
            - "db"
        environment:
            - POSTGRES_USER=supermaster
            - POSTGRES_PASSWORD=password1

    client:
        build: ./client
        command: npm run start 
        volumes:
            - ./client:/usr/src/app
            - /usr/src/app/node_modules
        ports:
            - "9000:3000"

